export enum TransactionType {
    OUTGOING_TRAN = 'OUTGOING_TRAN',
    INCOMING_TRAN = 'INCOMING_TRAN',
    INCOMING_REFUND_TRAN = 'INCOMING_REFUND_TRAN',
    CREDIT_ADJ_TRAN = 'CREDIT_ADJ_TRAN',
    DEBIT_ADJ_TRAN = 'DEBIT_ADJ_TRAN',
    RESUBMIT_TRAN = 'RESUBMIT_TRAN',
    REPOST_TRAN = 'REPOST_TRAN',
    REFUND_TRAN = 'REFUND_TRAN',
}